# Generated by Django 4.1.5 on 2023-02-06 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_alter_alumno_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='nomCarrera',
            new_name='carrera',
        ),
    ]
